name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: game3-back:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Set vips install path
        id: vips-path
        run: echo "dir=${HOME}/vips" >> $GITHUB_OUTPUT
      - name: Cache libvips
        uses: actions/cache@v4
        id: cache-vips
        with:
          path: ${{ steps.vips-path.outputs.dir }}
          key: ${{ runner.os }}-vips-${{ hashFiles('scripts/install-libvips.sh') }}
      - name: Install dependencies
        if: steps.cache-vips.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libexpat1-dev \
            libtiff5-dev \
            libspng-dev \
            libjpeg-turbo8-dev \
            meson \
            ninja-build \
            wget
      - name: Install libvips
        if: steps.cache-vips.outputs.cache-hit != 'true'
        run: ./scripts/install-libvips.sh ${{ steps.vips-path.outputs.dir }}
      - name: Copy libvips to global
        run: sudo cp -r ${{ steps.vips-path.outputs.dir }}/* /usr/local/
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
#  test-unit:
#    name: Unit Test
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version-file: ./go.mod
#      - run: make test-unit
#
#  test-integration:
#    name: Integration Test
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version-file: ./go.mod
#      - run: make test-integration
